Census address format
ONSdigital/census-rm-action-service pull request #3
Opened 2019-03-25 14:32 UTC by AdamHawtin

# Motivation and Context
The address format is changing for census attributes, including an address line 3. This PR brings the [actionsvc-api](https://github.com/ONSdigital/rm-actionsvc-api) classes into this project to alter them where they were previously imported as a dependency. Also renames some social specific code to census where it has now been repurposed.

# What has changed
- Bring in actionsvc-api transport classes, xsd's and tests
- Add pom goals to generate sources from xsd's
- Add address line 3 to the action address xsd
- Add test for sample attributes request decorator
- Rename repurposed social specific code to census and update tests accordingly 

# How to test?
This is waiting on changes to the casesvc, actionexportersvc and sample loader before it can easily be manually tested.

# Links
https://trello.com/c/e9iWXgje/517-rmc-83-load-hh-sample-and-generate-print-file-to-census-spec-13

2019-03-25 14:33 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-83 Load HH sample and generate print file to Census spec [13]](https://trello.com/c/e9iWXgje/517-rmc-83-load-hh-sample-and-generate-print-file-to-census-spec-13)

2019-03-26 15:57 UTC, philwhiles commented
Tuppence from the original developer ... the api projects were there for good reason - any other service wanting to call the action service will need its own copy of all those DTOs or its own copy of the XSD. Copy and paste programming **never** a good idea, because we know where that will lead. And the Case service for instance cannot have a dependency on action-service without pulling **all** of its code into its own jar.

2019-03-27 11:38 UTC, davidmort commented
whilst i'd agree that copy and paste is not always a good idea, i'd also argue that shared models between microservices is a bad idea, we much prefer a bit of duplication over tight coupling.

the reality of the api projects is that the code surrounding them still has to change when the apis change, and also the api's don't change enough to warrant having a specific pipeline/deployment for them or the extra overhead of managing the dependency. it's far easier just to wrap the code up in the app.  

Our intention is to decouple the RM services, reduce the point to point apis calls and replace with an event driven approach hence reducing the need for sharing api models even further

2019-03-28 07:53 UTC, LukeLoze1 requested changes
Looks ok to me.  Works with my local system.  Only issue would be to remove obviously unused actionTypes

2019-03-28 07:53 UTC, LukeLoze1 commented on src/main/java/uk/gov/ons/ctp/response/action/representation/ActionType.java
> +  BSNOT("BSNOT"),
Can the old action types be removed?

2019-04-01 10:05 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/ctp/response/action/representation/ActionType.java
> +  BSNOT("BSNOT"),
Not without deleting or re-writing a number of tests, I've created a ticket for this.

2019-04-02 11:01 UTC, liamtoozer approved these changes
Looks good to me. Ran tests locally from the other branches as well.

2019-04-02 11:18 UTC, liamtoozer commented on src/main/java/uk/gov/ons/ctp/response/action/scheduled/distribution/ActionDistributor.java
> +      return socialActionProcessingService;
Is it worth changing this name to `censusActionProcessingService`?

2019-04-03 10:57 UTC, NickGrantX approved these changes
LGTM 👍

2019-04-03 11:09 UTC, LukeLoze1 approved these changes

2019-04-03 11:10 UTC, hbrace approved these changes

2019-04-03 11:49 UTC, merged